.PHONY: ALL SERVER WORKSTATION CLEAN

ALL:

WORKSTATION:
	curl -o ~/.config/kitty/3024_Night.conf https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/3024_Night.conf
	curl -o ~/.config/kitty/MaterialDark.conf https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/MaterialDark.conf
	../../scripts/install kitty.conf ~/.config/kitty/kitty.conf

SERVER:

CLEAN:
	$(RM) -r ~/.config/kitty
