#!/bin/bash
#
# Author: Juraj Marcin <juraj@jurajmarcin.com>
#
# Usage ./dunststatus [OPTIONS] [ACTION]
#
# Options:
#
#   --icon-off ICON
#       notifications off (default: N)
#
#   --icon-on ICON
#       notifications on (default: Y)
#
#   --color-off HEX_COLOR
#       notifications off color (default: none)
#
#   --color-on HEX_COLOR
#       notifications on color (default: none)
#
# Actions:
#
#   toggle
#       toggle notifications
#   show
#       only shows status (default action)

ICON_OFF=N
ICON_ON=Y
COLOR_ON=
COLOR_OFF=

eval set -- `getopt --longoptions "icon-off:,icon-on:,color-off:,color-on:" -- "" "$@"`

while true; do
    case "$1" in
        --icon-off)
            ICON_OFF="$2"
            shift 2
            ;;
        --icon-on)
            ICON_ON="$2"
            shift 2
            ;;
        --color-off)
            COLOR_OFF="$2"
            shift 2
            ;;
        --color-on)
            COLOR_ON="$2"
            shift 2
            ;;
        "--")
            shift
            break
            ;;
    esac
done

ACTION="$1"

if [ "$ACTION" = "toggle" ]; then
    dunstctl set-paused toggle
fi

if [ "`dunstctl is-paused`" = "true" ]; then
    icon="$ICON_OFF"
    color="$COLOR_OFF"
else
    icon="$ICON_ON"
    color="$COLOR_ON"
fi

if [ -n "$color" ]; then
    echo "%{F$color}$icon%{F-}"
else
    echo "$icon"
fi
