#!/bin/bash

ICON_ON=Y
ICON_OFF=N
ICON_SYNC=S

eval set -- `getopt --longoptions "icon-on:,icon-off:,icon-sync:,color-new:" -- "u:d:s:n:" "$@"`

while true; do
    case "$1" in
        "-u"|"--icon-on")
            ICON_ON="$2"
            shift 2
            ;;
        "-d"|"--icon-off")
            ICON_OFF="$2"
            shift 2
            ;;
        "-s"|"--icon-sync")
            ICON_SYNC="$2"
            shift 2
            ;;
        "-n"|"--color-new")
            COLOR_NEW="$2"
            shift 2
            ;;
        "--")
            shift
            break
            ;;
    esac
done

ACTION=$1
MAILBOX=$2
MAILDIR=$3

get_current_icon() {

    if [ "`find "$MAILDIR" -type f -not -name '*2,*S*' -not -name '.*' -not -path '*Archive*' | wc -l`" -ne 0 ]; then
        color="$COLOR_NEW"
    else
        color=""
    fi

    if [ "`systemctl --user is-active "mbsync@$MAILBOX.timer"`" = "active" ]; then
        icon="$ICON_ON"
    else
        icon="$ICON_OFF"
    fi

    service_status="`systemctl --user is-active "mbsync@$MAILBOX.service"`"
    if [ "$service_status" = "active" -o "$service_status" = "activating" ]; then
        icon="$ICON_SYNC"
    fi

    if [ -n "$color" ]; then
        echo "%{F$color}$icon%{F-}"
    else
        echo "$icon"
    fi
}

case "$ACTION" in
    tail)
        get_current_icon

        journalctl --follow --output cat --user --unit "mbsync@$MAILBOX.timer" --unit "mbsync@$MAILBOX.service" \
                | while read -r; do
            get_current_icon
        done
    ;;
    show)
        get_current_icon
    ;;
    toggle)
        if [ "`systemctl --user is-active "mbsync@$MAILBOX.timer"`" = "active" ]; then
            systemctl --user stop "mbsync@$MAILBOX.timer"
        else
            systemctl --user start "mbsync@$MAILBOX.timer"
        fi
    ;;
    sync)
        systemctl --user start "mbsync@$MAILBOX.service"
    ;;
    *)
        exit 1
    ;;
esac
