#!/bin/bash

ICON_ON=Y
ICON_OFF=N

eval set -- `getopt --longoptions "icon-on:,icon-off:" -- "u:d:" "$@"`

while true; do
    case "$1" in
        "-u"|"--icon-on")
            ICON_ON="$2"
            shift 2
            ;;
        "-d"|"--icon-off")
            ICON_OFF="$2"
            shift 2
            ;;
        "--")
            shift
            break
            ;;
    esac
done

ACTION="$1"
UNIT="$2"

get_current_icon() {
    if [ "`systemctl --user is-active "$UNIT"`" = "active" ]; then
        echo "$ICON_ON"
    else
        echo "$ICON_OFF"
    fi
}

case "$ACTION" in
    tail)
        get_current_icon

        journalctl --follow --output cat --user --unit "$UNIT" \
                | while read -r; do
            get_current_icon
        done
    ;;
    show)
        get_current_icon
    ;;
    toggle)
        if [ "`systemctl --user is-active "$UNIT"`" = "active" ]; then
            systemctl --user stop "$UNIT"
        else
            systemctl --user start "$UNIT"
        fi
    ;;
    *)
        exit 1
    ;;
esac
